# Generated by Django 3.2.11 on 2022-04-19 14:49

import ckeditor_uploader.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guidage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=100, unique=True)),
                ('lib1', models.CharField(max_length=255)),
                ('affiche', models.BooleanField()),
                ('ordre', models.PositiveSmallIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('lib2', models.CharField(blank=True, max_length=255)),
                ('desc', models.TextField(blank=True, null=True)),
                ('durée', models.CharField(blank=True, max_length=100)),
                ('puht', models.DecimalField(blank=True, decimal_places=2, max_digits=6)),
                ('promo', models.BooleanField()),
                ('nouveau', models.BooleanField()),
                ('img', models.ImageField(blank=True, help_text='300px x 300px', null=True, upload_to='img/')),
                ('imgAlt', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lib', models.CharField(max_length=255, null=True)),
                ('ordre', models.PositiveSmallIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now=True)),
                ('affiche', models.BooleanField()),
                ('ordre', models.PositiveSmallIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('content_upload', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('theme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.theme')),
            ],
        ),
    ]
