# Generated by Django 3.2.11 on 2022-04-19 14:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=100, unique=True)),
                ('lib1', models.CharField(max_length=255)),
                ('affiche', models.BooleanField()),
                ('ordre', models.PositiveSmallIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('lib2', models.CharField(blank=True, max_length=255)),
                ('desc', models.TextField(blank=True, null=True)),
                ('durée', models.CharField(blank=True, max_length=100)),
                ('puht', models.DecimalField(blank=True, decimal_places=2, max_digits=6)),
                ('promo', models.BooleanField()),
                ('nouveau', models.BooleanField()),
                ('presentation', models.BooleanField()),
                ('img', models.ImageField(blank=True, help_text='300px x 300px', null=True, upload_to='img/')),
                ('imgAlt', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Guidage',
        ),
        migrations.RemoveField(
            model_name='article',
            name='theme',
        ),
        migrations.DeleteModel(
            name='Theme',
        ),
    ]
